export const LOGIN_LOAD = "LOGIN_LOAD";
export const LOGIN_LOAD_SUCCESS = "LOGIN_LOAD_SUCCESS";
export const LOGIN_LOAD_FAIL = "LOGIN_LOAD_FAIL";
export const CURRENT_USER_SUCC = "CURRENT_USER_SUCC";
export const CURRENT_USER_FAIL = "CURRENT_USER_FAIL";
